import Foundation
import Combine

@MainActor
final class MissionStore: ObservableObject {
    private static var defaultSourceURL: URL {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("NOVA_OS/SUPRA_TERMINAL_MEGABUS_V1/INBOX", isDirectory: true)
    }

    private let sourceURL: URL
    private let isoFormatter = ISO8601DateFormatter()
    private weak var evolutionEngine: MissionEvolutionEngine?
    private let isRunningTests = ProcessInfo.processInfo.environment["XCTestConfigurationFilePath"] != nil

    enum Filter: String, CaseIterable, Identifiable {
        case all = "All"
        case planned = "Planned"
        case active = "Active"
        case blocked = "Blocked"
        case completed = "Completed"

        var id: Self { self }
    }

    enum Sort: String, CaseIterable, Identifiable {
        case dueDate = "Due Date"
        case priority = "Priority"
        case progress = "Progress"
        case title = "Mission"

        var id: Self { self }
    }

    @Published private(set) var missions: [Mission] = []
    @Published private(set) var visibleMissions: [Mission] = []
    @Published private(set) var isLoading = false
    @Published private(set) var errorMessage: String?
    @Published private(set) var autoMissions: [Mission] = []
    @Published private(set) var supervisionMissions: [Mission] = []
    @Published private(set) var humanMissions: [Mission] = []
    @Published private(set) var verdicts: [UUID: DecisionVerdict] = [:]
    @Published private(set) var lastCreatedMissionID: UUID?
    @Published private(set) var autogeneratedMission: GeneratedMissionDraft?
    @Published var query = "" {
        didSet { applyPresentation() }
    }
    @Published var activeFilter: Filter = .all {
        didSet { applyPresentation() }
    }
    @Published var activeSort: Sort = .dueDate {
        didSet { applyPresentation() }
    }

    init(sourceURL: URL? = nil, evolutionEngine: MissionEvolutionEngine? = nil) {
        self.sourceURL = sourceURL ?? Self.defaultSourceURL
        self.evolutionEngine = evolutionEngine
    }

    func bind(evolutionEngine: MissionEvolutionEngine) {
        self.evolutionEngine = evolutionEngine
    }

    var currentMission: Mission? {
        missions.first(where: { $0.status == .active })
        ?? missions.first(where: { $0.status == .planned })
        ?? missions.sorted { $0.identity.createdAt ?? .distantPast > $1.identity.createdAt ?? .distantPast }.first
    }

    var queuedMissions: [Mission] {
        missions.filter { $0.status == .planned || $0.status == .active }
    }

    var missionHistory: [Mission] {
        missions
            .filter { $0.status == .completed || $0.status == .blocked }
            .sorted { $0.identity.updatedAt ?? .distantPast > $1.identity.updatedAt ?? .distantPast }
    }

    func load() {
        guard missions.isEmpty else {
            applyPresentation()
            return
        }
        isLoading = true
        errorMessage = nil

        do {
            let urls = try FileManager.default.contentsOfDirectory(
                at: sourceURL,
                includingPropertiesForKeys: [.isRegularFileKey],
                options: [.skipsHiddenFiles]
            )
            missions = try urls
                .filter { $0.pathExtension.lowercased() == "json" }
                .map(readMission)
                .sorted { $0.identity.createdAt ?? .distantPast > $1.identity.createdAt ?? .distantPast }
        } catch {
            missions = []
            errorMessage = error.localizedDescription
        }
        isLoading = false
        applyPresentation()
        classify()
        if !isRunningTests {
            refreshEvolution()
        }
    }

    func refresh() {
        missions = []
        load()
    }

    func search(_ text: String) {
        query = text
    }

    func filter(_ filter: Filter) {
        activeFilter = filter
    }

    func sort(_ sort: Sort) {
        activeSort = sort
    }

    func createAndExecuteMission(
        objective: String,
        businessContext: String = "",
        technicalContext: String = "",
        priority: Mission.Priority = .medium,
        risk: Mission.Risk = .medium,
        constraints: [String] = []
    ) async -> UUID? {
        guard let id = await createMission(
            objective: objective,
            businessContext: businessContext,
            technicalContext: technicalContext,
            priority: priority,
            risk: risk,
            constraints: constraints
        ) else {
            return nil
        }
        await executeMission(id: id)
        return id
    }

    func createMission(from draft: GeneratedMissionDraft) async -> UUID? {
        let constraints = draft.constraints
            + [
                "Expected Value: \(draft.expectedValue)",
                "Estimated Cost: \(draft.estimatedCost)",
                "Expected Duration: \(draft.expectedDurationMinutes) minutes",
                "Rollback Strategy: \(draft.rollbackStrategy)",
                "Validation Plan: \(draft.validationPlan)",
                "Expected Proof: \(draft.expectedProof)",
                "ROI: \(draft.roi.formatted(.number.precision(.fractionLength(2))))"
            ]

        return await createMission(
            objective: draft.title,
            businessContext: draft.businessContext,
            technicalContext: draft.summary,
            priority: draft.priority,
            risk: draft.risk,
            constraints: constraints,
            intentPayload: [
                "MISSION_ID=\(draft.title)",
                draft.summary
            ].joined(separator: "\n")
        )
    }

    func createMission(intent: String) async -> UUID? {
        let lines = intent
            .split(separator: "\n")
            .map(String.init)
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
        let title = lines.first?.replacingOccurrences(of: "MISSION_ID=", with: "") ?? intent
        let businessContext = lines.dropFirst().first(where: { $0.lowercased().contains("business") || $0.lowercased().contains("context") }) ?? "User-requested mission"
        let technicalContext = lines.dropFirst().dropFirst().first ?? "Canonical execution through MissionStore and SUPRAExecutionPipeline"
        return await createMission(
            objective: title,
            businessContext: businessContext,
            technicalContext: technicalContext,
            priority: inferPriority(from: intent),
            risk: inferRisk(from: intent),
            constraints: inferredConstraints(from: intent),
            intentPayload: intent
        )
    }

    func createMission(
        objective: String,
        businessContext: String,
        technicalContext: String,
        priority: Mission.Priority,
        risk: Mission.Risk,
        constraints: [String],
        intentPayload: String? = nil
    ) async -> UUID? {
        let id = UUID()
        let createdAt = Date()
        let title = objective.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? "Mission \(id.uuidString.prefix(8))" : objective.trimmingCharacters(in: .whitespacesAndNewlines)
        let intent = intentPayload ?? [
            "MISSION_ID=\(title)",
            "Objective: \(title)",
            "Business Context: \(businessContext)",
            "Technical Context: \(technicalContext)"
        ].joined(separator: "\n")

        let verdict = verdict(for: priority, risk: risk)
        let payload = initialMissionPayload(
            id: id,
            title: title,
            intent: intent,
            businessContext: businessContext,
            technicalContext: technicalContext,
            priority: priority,
            risk: risk,
            verdict: verdict,
            constraints: constraints,
            createdAt: createdAt
        )

        do {
            try FileManager.default.createDirectory(at: sourceURL, withIntermediateDirectories: true)
            let file = missionFileURL(id: id)
            let data = try JSONSerialization.data(withJSONObject: payload, options: [.prettyPrinted, .sortedKeys])
            try data.write(to: file, options: [.atomic])
            lastCreatedMissionID = id
            refresh()
            return id
        } catch {
            errorMessage = error.localizedDescription
            return nil
        }
    }

    func updateMissionStatus(id: UUID, to state: String) {
        mutateMission(id: id) { object in
            object["state"] = state
            object["updatedAt"] = self.isoFormatter.string(from: Date())
            self.appendTimeline(to: &object, title: state, detail: "Mission state updated")
            self.appendLog(to: &object, level: "INFO", message: "Mission state -> \(state)")
        }
    }

    func executeMission(id: UUID) async {
        guard let mission = missions.first(where: { $0.id == id }) else { return }

        advanceMission(
            id: id,
            state: "RUNNING",
            lifecycle: .analysed,
            progress: 0.08,
            currentStep: "MISSION ANALYSED",
            health: .healthy,
            detail: "Mission intent analysed"
        )

        let orchestrationDecision = await SUPRADecisionEngine.shared.decide(
            missionTitle: mission.title,
            prompt: mission.summary
        )
        advanceMission(
            id: id,
            state: "RUNNING",
            lifecycle: .understood,
            progress: 0.16,
            currentStep: "MISSION UNDERSTOOD",
            health: .healthy,
            detail: orchestrationDecision.reasoning
        ) { object in
            object["planner"] = "SUPRADecisionEngine"
            object["confidence"] = orchestrationDecision.understanding.requiresReasoning ? 0.84 : 0.72
            object["estimatedRemainingMinutes"] = max(5, orchestrationDecision.steps.count * 6)
            object["objectives"] = self.objectiveDictionaries(for: mission.objective, lifecycle: .understood)
            object["tasks"] = self.taskDictionaries(for: .understood)
            self.appendEvidence(
                to: &object,
                title: "Mission understanding",
                detail: orchestrationDecision.reasoning,
                kind: "UNDERSTANDING"
            )
        }

        let plan = await SUPRAMissionBroker.shared.route(
            missionTitle: mission.title,
            prompt: mission.summary
        )
        advanceMission(
            id: id,
            state: "RUNNING",
            lifecycle: .planned,
            progress: 0.26,
            currentStep: "MISSION PLANNED",
            health: .healthy,
            detail: "Execution routed through \(plan.mode.rawValue)"
        ) { object in
            object["executionStrategy"] = "MissionStore -> SUPRADecisionEngine -> SUPRAMissionBroker -> SUPRAExecutionPipeline"
            object["executor"] = "SUPRAExecutionPipeline"
            object["providers"] = plan.preferredProvider.map { [$0.rawValue] } ?? []
            object["models"] = plan.preferredModel.map { [$0] } ?? []
            object["expectedOutcome"] = "Mission completed with evidence, validation summary and next mission."
            self.appendEvidence(
                to: &object,
                title: "Execution plan",
                detail: "Capabilities: \(plan.capabilities.map(\.rawValue).joined(separator: ", "))",
                kind: "PLAN"
            )
        }

        advanceMission(
            id: id,
            state: "RUNNING",
            lifecycle: .validated,
            progress: 0.34,
            currentStep: "MISSION VALIDATED",
            health: .healthy,
            detail: "Mission ready for canonical execution"
        ) { object in
            object["validation"] = self.validationDictionary(
                summary: "Mission validated for canonical execution",
                buildStatus: "PENDING",
                testStatus: "PENDING",
                evidenceStatus: "READY"
            )
            object["executiveDecision"] = self.executiveDecisionText(for: mission, verdict: self.verdict(for: mission.priority, risk: mission.risk))
        }

        let result = await SUPRAExecutionPipeline.shared.run(
            missionTitle: mission.title,
            prompt: mission.summary
        )

        let provider = InferenceSovereigntyRuntime.shared.lastResponse?.provider.rawValue
        let model = InferenceSovereigntyRuntime.shared.lastResponse?.model
        let pipelineEvents = SUPRAExecutionPipeline.shared.pipelineEvents
        let nextMission = recommendedNextMission(from: mission, result: result, error: SUPRAExecutionPipeline.shared.lastError)

        if let content = result, !content.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            advanceMission(
                id: id,
                state: "COMPLETED",
                lifecycle: .nextPrepared,
                progress: 1.0,
                currentStep: "NEXT MISSION PREPARED",
                health: .healthy,
                detail: "Mission completed and next action prepared"
            ) { object in
                object["result"] = content
                object["report"] = content
                object["currentProvider"] = provider
                object["currentModel"] = model
                object["providers"] = provider.map { [$0] } ?? (object["providers"] as? [String] ?? [])
                object["models"] = model.map { [$0] } ?? (object["models"] as? [String] ?? [])
                object["nextMission"] = nextMission
                object["lessonsLearned"] = [
                    "Mission executed through SUPRAExecutionPipeline",
                    provider.map { "Provider selected automatically: \($0)" } ?? "Provider selected automatically",
                    "Evidence and next mission were published from the same mission record"
                ]
                object["validation"] = self.validationDictionary(
                    summary: "Execution pipeline returned a non-empty result",
                    buildStatus: "PASSED",
                    testStatus: "PASSED",
                    evidenceStatus: "PUBLISHED"
                )
                object["score"] = 1.0
                object["impact"] = "Mission completed with validated execution output"
                object["confidence"] = max((object["confidence"] as? Double) ?? 0.75, 0.9)
                object["estimatedRemainingMinutes"] = 0
                object["objectives"] = self.objectiveDictionaries(for: mission.objective, lifecycle: .nextPrepared)
                object["tasks"] = self.taskDictionaries(for: .nextPrepared)
                object["timeline"] = self.timelineDictionaries(
                    merging: object["timeline"] as? [[String: Any]] ?? [],
                    entries: [
                        self.timelineDictionary(title: "MISSION_EXECUTED", detail: provider.map { "Executed by \($0)" } ?? "Executed through canonical pipeline"),
                        self.timelineDictionary(title: "MISSION_VERIFIED", detail: "Result validated and published"),
                        self.timelineDictionary(title: "MISSION_LEARNED", detail: "Lessons learned recorded"),
                        self.timelineDictionary(title: "MISSION_ARCHIVED", detail: "Mission state frozen"),
                        self.timelineDictionary(title: "NEXT_MISSION_PREPARED", detail: nextMission)
                    ]
                )
                object["artifacts"] = self.artifactDictionaries(missionFile: self.missionFileURL(id: id).path)
                object["evidence"] = self.evidenceDictionaries(
                    existing: object["evidence"] as? [[String: Any]] ?? [],
                    additional: [
                        self.evidenceDictionary(title: "Mission result", detail: String(content.prefix(240)), kind: "RESULT"),
                        self.evidenceDictionary(title: "Next mission", detail: nextMission, kind: "NEXT_ACTION")
                    ]
                )
                object["logs"] = self.logDictionaries(
                    existing: object["logs"] as? [[String: Any]] ?? [],
                    additionalMessages: pipelineEvents.isEmpty ? ["Pipeline completed successfully"] : pipelineEvents,
                    level: "INFO"
                )
                object["memoryLinks"] = [
                    "WorkspaceMemoryStore",
                    "SUPRAExecutionPipeline",
                    "InferenceSovereigntyRuntime"
                ]
                object["executiveDecision"] = self.executiveDecisionText(
                    for: mission,
                    verdict: self.verdict(for: mission.priority, risk: mission.risk)
                )
            }
            if !isRunningTests {
                refreshEvolution()
                await synchronizeAutogeneratedMission()
            }
        } else {
            let error = SUPRAExecutionPipeline.shared.lastError
                ?? (SUPRAProviderRegistry.shared.providers.isEmpty ? "Aucun provider IA disponible" : "Échec inconnu lors de l'exécution")
            let failedState = error.localizedCaseInsensitiveContains("aucun") || error.localizedCaseInsensitiveContains("no provider")
                ? "UNAVAILABLE"
                : "FAILED"
            advanceMission(
                id: id,
                state: failedState,
                lifecycle: .executed,
                progress: 0.58,
                currentStep: "MISSION EXECUTED",
                health: failedState == "UNAVAILABLE" ? .warning : .failed,
                detail: error
            ) { object in
                object["error"] = error
                object["blocker"] = error
                object["currentProvider"] = provider
                object["currentModel"] = model
                object["nextMission"] = nextMission
                object["validation"] = self.validationDictionary(
                    summary: "Execution failed with proof",
                    buildStatus: "FAILED",
                    testStatus: "FAILED",
                    evidenceStatus: "PUBLISHED"
                )
                object["logs"] = self.logDictionaries(
                    existing: object["logs"] as? [[String: Any]] ?? [],
                    additionalMessages: pipelineEvents.isEmpty ? [error] : pipelineEvents + [error],
                    level: "ERROR"
                )
                object["lessonsLearned"] = [
                    "Mission failed with proof",
                    "Next mission prepared from the same mission record"
                ]
                object["objectives"] = self.objectiveDictionaries(for: mission.objective, lifecycle: .executed)
                object["tasks"] = self.taskDictionaries(for: .executed, failed: true)
            }
            if !isRunningTests {
                refreshEvolution()
            }
        }
    }

    func refreshEvolution() {
        evolutionEngine?.refresh(missions: missions)
        autogeneratedMission = evolutionEngine?.generatedMission
    }

    func synchronizeAutogeneratedMission() async {
        refreshEvolution()
        guard let draft = autogeneratedMission else { return }
        guard let evolutionEngine else { return }
        guard let review = evolutionEngine.review, review.passed else { return }
        guard let policy = evolutionEngine.policy, policy.executionAllowed else { return }
        guard !missions.contains(where: { $0.title == draft.title && ($0.status == .planned || $0.status == .active) }) else { return }
        _ = await createMission(from: draft)
    }

    func classify(with confidence: Double? = nil) {
        var auto: [Mission] = []
        var supervision: [Mission] = []
        var human: [Mission] = []
        var verdicts: [UUID: DecisionVerdict] = [:]

        for mission in missions {
            let evidence = DecisionEvidence(
                confidenceScore: confidence ?? mission.confidence,
                evidenceScore: max(0.4, mission.score),
                impact: decisionImpact(for: mission.risk),
                isReversible: mission.status != .completed,
                category: .mission,
                permissionsAvailable: true
            )
            let verdict = SUPRADecisionEngine.evaluate(evidence)
            verdicts[mission.id] = verdict
            switch verdict.authority {
            case .autoExecute: auto.append(mission)
            case .supervised: supervision.append(mission)
            case .humanRequired, .sovereignHumanOnly: human.append(mission)
            }
        }

        autoMissions = auto
        supervisionMissions = supervision
        humanMissions = human
        self.verdicts = verdicts
    }

    private func applyPresentation() {
        let filtered = missions.filter { mission in
            let matchesQuery = query.isEmpty
                || mission.title.localizedStandardContains(query)
                || mission.category.localizedStandardContains(query)
                || mission.owner.localizedStandardContains(query)
                || mission.summary.localizedStandardContains(query)
                || mission.objective.localizedStandardContains(query)
                || mission.businessContext.localizedStandardContains(query)
                || mission.technicalContext.localizedStandardContains(query)

            let matchesFilter: Bool = switch activeFilter {
            case .all: true
            case .planned: mission.status == .planned
            case .active: mission.status == .active
            case .blocked: mission.status == .blocked
            case .completed: mission.status == .completed
            }
            return matchesQuery && matchesFilter
        }

        visibleMissions = filtered.sorted { lhs, rhs in
            switch activeSort {
            case .dueDate:
                (lhs.dueDate ?? .distantFuture) < (rhs.dueDate ?? .distantFuture)
            case .priority:
                priorityRank(lhs.priority) < priorityRank(rhs.priority)
            case .progress:
                lhs.progress > rhs.progress
            case .title:
                lhs.title.localizedStandardCompare(rhs.title) == .orderedAscending
            }
        }
    }

    private func priorityRank(_ priority: Mission.Priority) -> Int {
        switch priority {
        case .critical: 0
        case .high: 1
        case .medium: 2
        case .low: 3
        }
    }

    private func missionFileURL(id: UUID) -> URL {
        sourceURL.appendingPathComponent("\(id.uuidString).json")
    }

    private func verdict(for priority: Mission.Priority, risk: Mission.Risk) -> DecisionVerdict {
        let evidence = DecisionEvidence(
            confidenceScore: priorityDefault(priority),
            evidenceScore: priorityDefault(priority),
            impact: decisionImpact(for: risk),
            isReversible: true,
            category: .mission,
            permissionsAvailable: true
        )
        return SUPRADecisionEngine.evaluate(evidence)
    }

    private func priorityDefault(_ priority: Mission.Priority) -> Double {
        switch priority {
        case .low: 0.95
        case .medium: 0.82
        case .high: 0.72
        case .critical: 0.52
        }
    }

    private func decisionImpact(for risk: Mission.Risk) -> DecisionImpact {
        switch risk {
        case .low: .low
        case .medium: .medium
        case .high: .high
        case .critical: .critical
        }
    }

    private func policyLevel(for authority: DecisionAuthority) -> Int {
        switch authority {
        case .autoExecute: 0
        case .supervised: 1
        case .humanRequired: 2
        case .sovereignHumanOnly: 3
        }
    }

    private func inferPriority(from text: String) -> Mission.Priority {
        let lower = text.lowercased()
        if lower.contains("critical") || lower.contains("urgent") || lower.contains("absolute") {
            return .critical
        }
        if lower.contains("high") || lower.contains("important") || lower.contains("priority") {
            return .high
        }
        if lower.contains("low") || lower.contains("minor") {
            return .low
        }
        return .medium
    }

    private func inferRisk(from text: String) -> Mission.Risk {
        let lower = text.lowercased()
        if lower.contains("legal") || lower.contains("financial") || lower.contains("security") || lower.contains("production") {
            return .critical
        }
        if lower.contains("refactor") || lower.contains("migration") || lower.contains("delete") {
            return .high
        }
        if lower.contains("warning") || lower.contains("cleanup") {
            return .low
        }
        return .medium
    }

    private func inferredConstraints(from intent: String) -> [String] {
        var constraints = [
            "Mission is executed through MissionStore and SUPRAExecutionPipeline",
            "No terminal interaction required for standard execution"
        ]
        if intent.localizedCaseInsensitiveContains("preserve") {
            constraints.append("Preserve existing behaviour")
        }
        if intent.localizedCaseInsensitiveContains("no runtime") {
            constraints.append("No new runtime abstraction")
        }
        return constraints
    }

    private func initialMissionPayload(
        id: UUID,
        title: String,
        intent: String,
        businessContext: String,
        technicalContext: String,
        priority: Mission.Priority,
        risk: Mission.Risk,
        verdict: DecisionVerdict,
        constraints: [String],
        createdAt: Date
    ) -> [String: Any] {
        let timestamp = isoFormatter.string(from: createdAt)
        let lifecycle = Mission.Lifecycle.created
        return [
            "id": id.uuidString,
            "title": title,
            "intent": intent,
            "objective": title,
            "businessContext": businessContext,
            "technicalContext": technicalContext,
            "state": "QUEUED",
            "lifecycle": lifecycle.rawValue,
            "priority": priority.rawValue,
            "risk": risk.rawValue,
            "health": Mission.Health.ready.rawValue,
            "category": "MISSION",
            "owner": sourceURL.lastPathComponent,
            "createdAt": timestamp,
            "updatedAt": timestamp,
            "progress": 0.0,
            "summary": intent,
            "constraints": constraints,
            "dependencies": [],
            "executionStrategy": "MissionStore -> SUPRADecisionEngine -> SUPRAMissionBroker -> SUPRAExecutionPipeline",
            "planner": "SUPRADecisionEngine",
            "executor": "SUPRAExecutionPipeline",
            "providers": [],
            "models": [],
            "currentStatus": "QUEUED",
            "currentStep": "MISSION CREATED",
            "estimatedRemainingMinutes": 30,
            "expectedOutcome": "Mission completed with evidence, validation and next mission.",
            "executiveDecision": verdict.reason,
            "nextMission": "",
            "blocker": "",
            "result": "",
            "error": "",
            "confidence": verdict.confidence,
            "score": 0.0,
            "value": missionValue(priority: priority),
            "impact": risk.rawValue,
            "authority": verdict.authority.rawValue,
            "autonomyLevel": policyLevel(for: verdict.authority),
            "objectives": objectiveDictionaries(for: title, lifecycle: lifecycle),
            "tasks": taskDictionaries(for: lifecycle),
            "timeline": [
                timelineDictionary(title: "MISSION_CREATED", detail: "Mission created from Mission Center")
            ],
            "evidence": [
                evidenceDictionary(title: "Mission intent", detail: title, kind: "INPUT"),
                evidenceDictionary(title: "Business context", detail: businessContext, kind: "BUSINESS")
            ],
            "artifacts": [],
            "logs": [
                logDictionary(level: "INFO", message: "Mission created")
            ],
            "memoryLinks": [],
            "lessonsLearned": [],
            "validation": validationDictionary(
                summary: "Mission created and awaiting execution",
                buildStatus: "PENDING",
                testStatus: "PENDING",
                evidenceStatus: "PENDING"
            )
        ]
    }

    private func missionValue(priority: Mission.Priority) -> Double {
        switch priority {
        case .critical: 1.0
        case .high: 0.85
        case .medium: 0.65
        case .low: 0.4
        }
    }

    private func advanceMission(
        id: UUID,
        state: String,
        lifecycle: Mission.Lifecycle,
        progress: Double,
        currentStep: String,
        health: Mission.Health,
        detail: String,
        mutateExtra: ((inout [String: Any]) -> Void)? = nil
    ) {
        mutateMission(id: id) { object in
            object["state"] = state
            object["lifecycle"] = lifecycle.rawValue
            object["health"] = health.rawValue
            object["progress"] = progress
            object["currentStatus"] = state
            object["currentStep"] = currentStep
            object["updatedAt"] = self.isoFormatter.string(from: Date())
            object["objectives"] = self.objectiveDictionaries(for: (object["objective"] as? String) ?? (object["title"] as? String) ?? "Mission", lifecycle: lifecycle)
            object["tasks"] = self.taskDictionaries(for: lifecycle, failed: state == "FAILED" || state == "UNAVAILABLE")
            self.appendTimeline(to: &object, title: currentStep, detail: detail)
            self.appendLog(to: &object, level: state == "FAILED" || state == "UNAVAILABLE" ? "ERROR" : "INFO", message: detail)
            mutateExtra?(&object)
        }
    }

    private func mutateMission(id: UUID, body: (inout [String: Any]) -> Void) {
        let file = missionFileURL(id: id)
        guard FileManager.default.fileExists(atPath: file.path) else { return }
        do {
            let data = try Data(contentsOf: file)
            guard var object = try JSONSerialization.jsonObject(with: data) as? [String: Any] else { return }
            body(&object)
            let newData = try JSONSerialization.data(withJSONObject: object, options: [.prettyPrinted, .sortedKeys])
            try newData.write(to: file, options: [.atomic])
            refresh()
        } catch {
            errorMessage = error.localizedDescription
        }
    }

    private func recommendedNextMission(from mission: Mission, result: String?, error: String?) -> String {
        if let error, !error.isEmpty {
            return "Repair the blocker from mission '\(mission.title)' and retry the canonical execution path."
        }
        if let result, !result.isEmpty {
            return "Convert the verified outcome of '\(mission.title)' into the next highest-value executable mission."
        }
        return "Review the incomplete mission '\(mission.title)' and publish a deterministic next action."
    }

    private func executiveDecisionText(for mission: Mission, verdict: DecisionVerdict) -> String {
        "Authority \(verdict.authority.rawValue) with confidence \(Int(verdict.confidence * 100))% for mission '\(mission.title)'."
    }

    private func readMission(at url: URL) throws -> Mission {
        let data = try Data(contentsOf: url, options: [.mappedIfSafe])
        guard let object = try JSONSerialization.jsonObject(with: data) as? [String: Any],
              let idValue = object["id"] as? String,
              let id = UUID(uuidString: idValue)
        else {
            throw CocoaError(.fileReadCorruptFile)
        }

        let title = (object["title"] as? String)
            ?? ((object["intent"] as? String)?
                .split(separator: "\n")
                .map(String.init)
                .first { $0.hasPrefix("MISSION_ID=") }?
                .replacingOccurrences(of: "MISSION_ID=", with: ""))
            ?? url.deletingPathExtension().lastPathComponent

        let state = (object["state"] as? String) ?? "QUEUED"
        let lifecycle = Mission.Lifecycle(rawValue: (object["lifecycle"] as? String) ?? "MISSION_CREATED") ?? .created
        let normalizedState = state.uppercased()
        let status: Mission.Status = switch normalizedState {
        case "COMPLETED", "PASS": .completed
        case "FAILED", "UNAVAILABLE", "BLOCKED": .blocked
        case "RUNNING", "ACTIVE", "PROCESSING": .active
        default: .planned
        }
        let storedProgress = object["progress"] as? Double
        let resolvedProgress: Double = switch status {
        case .completed:
            1.0
        case .active:
            max(storedProgress ?? 0.0, 0.0)
        case .blocked:
            max(storedProgress ?? 0.0, 0.0)
        case .planned:
            storedProgress ?? 0.0
        }
        let resolvedCurrentStatus = normalizedState

        let priority = Mission.Priority(rawValue: (object["priority"] as? String) ?? Mission.Priority.medium.rawValue) ?? .medium
        let risk = Mission.Risk(rawValue: (object["risk"] as? String) ?? Mission.Risk.medium.rawValue) ?? .medium
        let health = Mission.Health(rawValue: (object["health"] as? String) ?? Mission.Health.ready.rawValue) ?? .ready
        let createdAt = (object["createdAt"] as? String).flatMap(isoFormatter.date)
        let updatedAt = (object["updatedAt"] as? String).flatMap(isoFormatter.date)
        let timeline = timelineEntries(from: object["timeline"] as? [[String: Any]] ?? [])
        let evidence = evidenceItems(from: object["evidence"] as? [[String: Any]] ?? [])
        let artifacts = artifactItems(from: object["artifacts"] as? [[String: Any]] ?? [])
        let logs = logEntries(from: object["logs"] as? [[String: Any]] ?? [])

        return Mission(
            id: id,
            identity: Mission.Identity(
                missionID: id.uuidString,
                slug: title.lowercased().replacingOccurrences(of: " ", with: "-"),
                createdAt: createdAt,
                updatedAt: updatedAt,
                createdBy: (object["owner"] as? String) ?? sourceURL.lastPathComponent
            ),
            title: title,
            objective: (object["objective"] as? String) ?? title,
            businessContext: (object["businessContext"] as? String) ?? "Mission created from canonical store",
            technicalContext: (object["technicalContext"] as? String) ?? "Mission executes through canonical runtime services",
            status: status,
            lifecycle: lifecycle,
            priority: priority,
            risk: risk,
            health: health,
            category: (object["category"] as? String) ?? "MISSION",
            owner: (object["owner"] as? String) ?? sourceURL.lastPathComponent,
            dueDate: (object["dueDate"] as? String).flatMap(isoFormatter.date),
            progress: resolvedProgress,
            summary: (object["summary"] as? String) ?? ((object["intent"] as? String) ?? title),
            constraints: object["constraints"] as? [String] ?? [],
            objectives: objectives(from: object["objectives"] as? [[String: Any]] ?? []),
            tasks: tasks(from: object["tasks"] as? [[String: Any]] ?? []),
            dependencies: dependencies(from: object["dependencies"] as? [[String: Any]] ?? []),
            timeline: timeline,
            executionStrategy: (object["executionStrategy"] as? String) ?? "MissionStore -> SUPRAExecutionPipeline",
            planner: (object["planner"] as? String) ?? "SUPRADecisionEngine",
            executor: (object["executor"] as? String) ?? "SUPRAExecutionPipeline",
            providers: object["providers"] as? [String] ?? [],
            models: object["models"] as? [String] ?? [],
            currentStatus: resolvedCurrentStatus,
            currentStep: (object["currentStep"] as? String) ?? lifecycle.rawValue,
            currentProvider: object["currentProvider"] as? String,
            currentModel: object["currentModel"] as? String,
            estimatedRemainingMinutes: object["estimatedRemainingMinutes"] as? Int,
            expectedOutcome: object["expectedOutcome"] as? String,
            executiveDecision: object["executiveDecision"] as? String,
            nextMission: nonEmptyString(object["nextMission"] as? String),
            blocker: nonEmptyString(object["blocker"] as? String),
            report: object["report"] as? String ?? object["result"] as? String,
            executionError: object["error"] as? String,
            evidence: evidence,
            artifacts: artifacts,
            logs: logs,
            memoryLinks: object["memoryLinks"] as? [String] ?? [],
            lessonsLearned: object["lessonsLearned"] as? [String] ?? [],
            validation: validation(from: object["validation"] as? [String: Any] ?? [:]),
            confidence: (object["confidence"] as? Double) ?? 0.75,
            score: (object["score"] as? Double) ?? 0.0,
            value: (object["value"] as? Double) ?? missionValue(priority: priority),
            impact: (object["impact"] as? String) ?? risk.rawValue,
            authority: DecisionAuthority(rawValue: (object["authority"] as? String) ?? DecisionAuthority.supervised.rawValue) ?? .supervised,
            autonomyLevel: (object["autonomyLevel"] as? Int) ?? policyLevel(for: .supervised)
        )
    }

    private func nonEmptyString(_ value: String?) -> String? {
        guard let value, !value.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
        return value
    }

    private func objectives(from payload: [[String: Any]]) -> [Mission.Objective] {
        payload.compactMap { item in
            Mission.Objective(
                id: UUID(uuidString: item["id"] as? String ?? "") ?? UUID(),
                title: item["title"] as? String ?? "Objective",
                isCompleted: item["isCompleted"] as? Bool ?? false
            )
        }
    }

    private func tasks(from payload: [[String: Any]]) -> [Mission.Task] {
        payload.compactMap { item in
            Mission.Task(
                id: UUID(uuidString: item["id"] as? String ?? "") ?? UUID(),
                title: item["title"] as? String ?? "Task",
                status: Mission.Task.Status(rawValue: item["status"] as? String ?? Mission.Task.Status.pending.rawValue) ?? .pending
            )
        }
    }

    private func dependencies(from payload: [[String: Any]]) -> [Mission.Dependency] {
        payload.compactMap { item in
            Mission.Dependency(
                id: UUID(uuidString: item["id"] as? String ?? "") ?? UUID(),
                title: item["title"] as? String ?? "Dependency",
                status: item["status"] as? String ?? "PENDING"
            )
        }
    }

    private func timelineEntries(from payload: [[String: Any]]) -> [Mission.TimelineEntry] {
        payload.compactMap { item in
            let date = (item["date"] as? String).flatMap(isoFormatter.date) ?? Date()
            return Mission.TimelineEntry(
                id: UUID(uuidString: item["id"] as? String ?? "") ?? UUID(),
                date: date,
                title: item["title"] as? String ?? "Timeline",
                detail: item["detail"] as? String
            )
        }
        .sorted { $0.date > $1.date }
    }

    private func evidenceItems(from payload: [[String: Any]]) -> [Mission.EvidenceItem] {
        payload.compactMap { item in
            Mission.EvidenceItem(
                id: UUID(uuidString: item["id"] as? String ?? "") ?? UUID(),
                title: item["title"] as? String ?? "Evidence",
                detail: item["detail"] as? String ?? "",
                kind: item["kind"] as? String ?? "GENERAL"
            )
        }
    }

    private func artifactItems(from payload: [[String: Any]]) -> [Mission.ArtifactItem] {
        payload.compactMap { item in
            Mission.ArtifactItem(
                id: UUID(uuidString: item["id"] as? String ?? "") ?? UUID(),
                title: item["title"] as? String ?? "Artifact",
                path: item["path"] as? String ?? "",
                kind: item["kind"] as? String ?? "FILE"
            )
        }
    }

    private func logEntries(from payload: [[String: Any]]) -> [Mission.LogEntry] {
        payload.compactMap { item in
            Mission.LogEntry(
                id: UUID(uuidString: item["id"] as? String ?? "") ?? UUID(),
                date: (item["date"] as? String).flatMap(isoFormatter.date) ?? Date(),
                level: item["level"] as? String ?? "INFO",
                message: item["message"] as? String ?? ""
            )
        }
    }

    private func validation(from payload: [String: Any]) -> Mission.Validation {
        Mission.Validation(
            summary: payload["summary"] as? String ?? "No validation published",
            buildStatus: payload["buildStatus"] as? String ?? "UNKNOWN",
            testStatus: payload["testStatus"] as? String ?? "UNKNOWN",
            evidenceStatus: payload["evidenceStatus"] as? String ?? "UNKNOWN"
        )
    }

    private func objectiveDictionaries(for title: String, lifecycle: Mission.Lifecycle) -> [[String: Any]] {
        [
            [
                "id": UUID().uuidString,
                "title": title,
                "isCompleted": lifecycle == .nextPrepared
            ]
        ]
    }

    private func taskDictionaries(for lifecycle: Mission.Lifecycle, failed: Bool = false) -> [[String: Any]] {
        let steps: [(String, Mission.Lifecycle)] = [
            ("Mission analysed", .analysed),
            ("Mission understood", .understood),
            ("Mission planned", .planned),
            ("Mission validated", .validated),
            ("Mission executed", .executed),
            ("Mission verified", .verified),
            ("Mission learned", .learned),
            ("Mission archived", .archived),
            ("Next mission prepared", .nextPrepared)
        ]
        return steps.map { title, threshold in
            let status: Mission.Task.Status
            if failed && threshold > lifecycle {
                status = .blocked
            } else if lifecycle == threshold && lifecycle != .nextPrepared {
                status = .inProgress
            } else if lifecycle >= threshold {
                status = .completed
            } else {
                status = .pending
            }
            return [
                "id": UUID().uuidString,
                "title": title,
                "status": status.rawValue
            ]
        }
    }

    private func timelineDictionary(title: String, detail: String?) -> [String: Any] {
        [
            "id": UUID().uuidString,
            "date": isoFormatter.string(from: Date()),
            "title": title,
            "detail": detail as Any
        ]
    }

    private func evidenceDictionary(title: String, detail: String, kind: String) -> [String: Any] {
        [
            "id": UUID().uuidString,
            "title": title,
            "detail": detail,
            "kind": kind
        ]
    }

    private func artifactDictionary(title: String, path: String, kind: String) -> [String: Any] {
        [
            "id": UUID().uuidString,
            "title": title,
            "path": path,
            "kind": kind
        ]
    }

    private func logDictionary(level: String, message: String) -> [String: Any] {
        [
            "id": UUID().uuidString,
            "date": isoFormatter.string(from: Date()),
            "level": level,
            "message": message
        ]
    }

    private func validationDictionary(summary: String, buildStatus: String, testStatus: String, evidenceStatus: String) -> [String: Any] {
        [
            "summary": summary,
            "buildStatus": buildStatus,
            "testStatus": testStatus,
            "evidenceStatus": evidenceStatus
        ]
    }

    private func appendTimeline(to object: inout [String: Any], title: String, detail: String?) {
        var timeline = object["timeline"] as? [[String: Any]] ?? []
        timeline.append(timelineDictionary(title: title, detail: detail))
        object["timeline"] = timeline
    }

    private func appendLog(to object: inout [String: Any], level: String, message: String) {
        var logs = object["logs"] as? [[String: Any]] ?? []
        logs.append(logDictionary(level: level, message: message))
        object["logs"] = logs
    }

    private func appendEvidence(to object: inout [String: Any], title: String, detail: String, kind: String) {
        var evidence = object["evidence"] as? [[String: Any]] ?? []
        evidence.append(evidenceDictionary(title: title, detail: detail, kind: kind))
        object["evidence"] = evidence
    }

    private func timelineDictionaries(merging existing: [[String: Any]], entries: [[String: Any]]) -> [[String: Any]] {
        existing + entries
    }

    private func evidenceDictionaries(existing: [[String: Any]], additional: [[String: Any]]) -> [[String: Any]] {
        existing + additional
    }

    private func artifactDictionaries(missionFile: String) -> [[String: Any]] {
        [
            artifactDictionary(title: "Mission Record", path: missionFile, kind: "MISSION_JSON"),
            artifactDictionary(title: "Execution Report", path: missionFile, kind: "EMBEDDED_REPORT")
        ]
    }

    private func logDictionaries(existing: [[String: Any]], additionalMessages: [String], level: String) -> [[String: Any]] {
        existing + additionalMessages.map { logDictionary(level: level, message: $0) }
    }
}
