import SwiftUI

// MARK: - Mission Surface View
//
// Reconnected to the Snapshot Bus (Ω6) per PROJECT PHOENIX.
// Reads mission data from ExecutiveSnapshotBus.shared.latestSnapshot
// instead of direct service access. MissionStore is retained only for
// write operations (create, execute, refresh).

struct MissionSurfaceView: View {
    @StateObject private var bus = ExecutiveSnapshotBus.shared
    @Binding var selection: String?

    @State private var objective = ""
    @State private var businessContext = ""
    @State private var technicalContext = ""
    @State private var priority: Mission.Priority = .medium
    @State private var risk: Mission.Risk = .medium
    @State private var isSubmitting = false
    private let isRunningTests = ProcessInfo.processInfo.environment["XCTestConfigurationFilePath"] != nil

    private var summary: ExecutiveContextSnapshot.MissionsSummary {
        bus.latestSnapshot.context.missionsSummary
    }

    private var store: MissionStore {
        SUPRACompositionRoot.shared.missionStore
    }

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 18) {
                hero
                composer
                currentMissionGrid
                autogeneratedMissionSection
                queueSection
                lessonsAndHistory
            }
            .padding(20)
            .frame(maxWidth: .infinity, alignment: .leading)
        }
        .background(Color.supraBackground)
        .onAppear {
            if selection == nil {
                selection = summary.current?.id ?? summary.visibleMissions.first?.id
            }
            if !isRunningTests {
                store.refreshEvolution()
            }
        }
    }

    private var hero: some View {
        VStack(alignment: .leading, spacing: 10) {
            Text("MISSION OPERATING SYSTEM")
                .font(.caption.weight(.bold))
                .tracking(2)
                .foregroundStyle(Color.supraAccent)
            Text("Mission is the canonical operating unit.")
                .font(.system(size: 28, weight: .bold, design: .rounded))
                .foregroundStyle(Color.supraText)
            Text("Create a mission once. SUPRA classifies it, routes it, executes it, validates it, updates memory, and prepares the next one.")
                .font(.system(size: 13))
                .foregroundStyle(Color.supraTextSecondary)
        }
        .padding(20)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Color.supraSurface)
        .clipShape(RoundedRectangle(cornerRadius: 18))
        .overlay(RoundedRectangle(cornerRadius: 18).stroke(Color.supraBorder, lineWidth: 1))
    }

    private var composer: some View {
        VStack(alignment: .leading, spacing: 12) {
            sectionTitle("Create Mission", systemImage: "flag.fill")
            TextField("Objective", text: $objective, axis: .vertical)
                .textFieldStyle(.roundedBorder)
            TextField("Business Context", text: $businessContext, axis: .vertical)
                .textFieldStyle(.roundedBorder)
            TextField("Technical Context", text: $technicalContext, axis: .vertical)
                .textFieldStyle(.roundedBorder)

            HStack(spacing: 12) {
                Picker("Priority", selection: $priority) {
                    ForEach(Mission.Priority.allCases, id: \.self) { level in
                        Text(level.rawValue).tag(level)
                    }
                }
                .pickerStyle(.menu)

                Picker("Risk", selection: $risk) {
                    ForEach(Mission.Risk.allCases, id: \.self) { level in
                        Text(level.rawValue).tag(level)
                    }
                }
                .pickerStyle(.menu)

                Spacer()

                Button {
                    submitMission()
                } label: {
                    HStack(spacing: 8) {
                        if isSubmitting {
                            ProgressView().scaleEffect(0.7)
                        }
                        Text(isSubmitting ? "Operating..." : "Launch Mission")
                            .font(.system(size: 13, weight: .semibold))
                    }
                    .padding(.horizontal, 16)
                    .padding(.vertical, 10)
                    .background(canSubmit ? Color.supraAccent : Color.supraTextTertiary)
                    .foregroundStyle(Color.white)
                    .clipShape(RoundedRectangle(cornerRadius: 10))
                }
                .buttonStyle(.plain)
                .disabled(!canSubmit || isSubmitting)
            }
        }
        .padding(18)
        .background(Color.supraSurface)
        .clipShape(RoundedRectangle(cornerRadius: 18))
        .overlay(RoundedRectangle(cornerRadius: 18).stroke(Color.supraBorder, lineWidth: 1))
    }

    private var currentMissionGrid: some View {
        let mission = summary.current
        return VStack(alignment: .leading, spacing: 12) {
            sectionTitle("Current Mission", systemImage: "scope")
            LazyVGrid(columns: [GridItem(.adaptive(minimum: 180), spacing: 12)], spacing: 12) {
                statCard("Current Mission", mission?.title ?? "No mission", "flag.fill", .supraAccent)
                statCard("Executive Decision", mission?.executiveDecision ?? "Awaiting mission", "checkmark.seal.fill", .supraOrange)
                statCard("Current Progress", mission.map { "\($0.progress.formatted(.percent.precision(.fractionLength(0))))" } ?? "0%", "chart.bar.fill", .supraBlue)
                statCard("Current Step", mission?.currentStep ?? "Mission not started", "point.3.connected.trianglepath.dotted", .supraTeal)
                statCard("Current Evidence", "\(mission?.evidenceCount ?? 0) items", "doc.text.magnifyingglass", .supraPurple)
                statCard("Current Risk", mission?.risk ?? "Medium", "exclamationmark.triangle.fill", .supraRed)
                statCard("Current Blocker", mission?.blocker ?? "None", "hand.raised.fill", mission?.blocker == nil ? .supraGreen : .supraRed)
                statCard("Current Executor", "SUPRAExecutionPipeline", "cpu.fill", .supraAccent)
                statCard("Current Provider", mission?.currentProvider ?? "Auto", "network", .supraTeal)
                statCard("Current Model", mission?.currentModel ?? "Auto", "brain.head.profile", .supraPurple)
                statCard("Remaining Time", mission?.estimatedRemainingMinutes.map { "\($0) min" } ?? "—", "timer", .supraBlue)
                statCard("Expected Outcome", mission?.expectedOutcome ?? "Mission output, evidence and next mission", "sparkles", .supraGreen)
                statCard("Next Action", mission?.nextMission ?? "Prepare a mission to see the next action", "arrow.right.circle.fill", .supraOrange)
                statCard("Mission Health", mission?.health ?? "Ready", "heart.text.square.fill", .supraGreen)
            }
        }
    }

    private var queueSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            sectionTitle("Mission Queue", systemImage: "list.bullet.rectangle.portrait")
            HStack(alignment: .top, spacing: 12) {
                queueCard(title: "Automatic", missions: summary.autoMissions, color: .supraGreen)
                queueCard(title: "Supervised", missions: summary.supervisionMissions, color: .supraOrange)
                queueCard(title: "Human", missions: summary.humanMissions, color: .supraRed)
            }
        }
    }

    private var autogeneratedMissionSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            sectionTitle("Next Auto-Generated Mission", systemImage: "wand.and.stars.inverse")
            missionPanel {
                if let draft = store.autogeneratedMission {
                    VStack(alignment: .leading, spacing: 10) {
                        HStack(alignment: .top) {
                            VStack(alignment: .leading, spacing: 4) {
                                Text(draft.title)
                                    .font(.system(size: 14, weight: .semibold))
                                    .foregroundStyle(Color.supraText)
                                Text(draft.objective)
                                    .font(.system(size: 12))
                                    .foregroundStyle(Color.supraTextSecondary)
                            }
                            Spacer()
                            Text(draft.authority.rawValue)
                                .font(.system(size: 10, weight: .bold))
                                .foregroundStyle(Color.supraAccent)
                        }

                        Text("Value: \(draft.expectedValue)")
                            .font(.system(size: 12))
                            .foregroundStyle(Color.supraText)
                        Text("ROI \(draft.roi.formatted(.number.precision(.fractionLength(2)))) · Confidence \(draft.confidence.formatted(.percent.precision(.fractionLength(0)))) · \(draft.expectedDurationMinutes) min")
                            .font(.system(size: 11))
                            .foregroundStyle(Color.supraTextSecondary)
                        Text("Validation: \(draft.validationPlan)")
                            .font(.system(size: 11))
                            .foregroundStyle(Color.supraTextSecondary)

                        HStack(spacing: 10) {
                            Button("Refresh Proposal") {
                                store.refreshEvolution()
                            }
                            .buttonStyle(.plain)
                            .padding(.horizontal, 12)
                            .padding(.vertical, 8)
                            .background(Color.supraGlass)
                            .clipShape(RoundedRectangle(cornerRadius: 10))

                            Button("Queue Mission") {
                                Task {
                                    if let id = await store.createMission(from: draft) {
                                        selection = id.uuidString
                                    }
                                }
                            }
                            .buttonStyle(.plain)
                            .padding(.horizontal, 12)
                            .padding(.vertical, 8)
                            .background(Color.supraAccent)
                            .foregroundStyle(Color.white)
                            .clipShape(RoundedRectangle(cornerRadius: 10))
                        }
                    }
                } else {
                    Text("No reviewed autogenerated mission is available yet.")
                        .font(.system(size: 12))
                        .foregroundStyle(Color.supraTextSecondary)
                }
            }
        }
    }

    private var lessonsAndHistory: some View {
        HStack(alignment: .top, spacing: 12) {
            VStack(alignment: .leading, spacing: 10) {
                sectionTitle("Recent Lessons", systemImage: "lightbulb.fill")
                missionPanel {
                    // Deep detail still accessed via MissionStore
                    let lessons = store.currentMission?.lessonsLearned ?? []
                    if lessons.isEmpty {
                        Text("Lessons will appear after mission execution.")
                            .font(.system(size: 12))
                            .foregroundStyle(Color.supraTextSecondary)
                    } else {
                        ForEach(Array(lessons.prefix(6).enumerated()), id: \.offset) { _, lesson in
                            Text(lesson)
                                .font(.system(size: 12))
                                .foregroundStyle(Color.supraText)
                                .frame(maxWidth: .infinity, alignment: .leading)
                        }
                    }
                }
            }
            .frame(maxWidth: .infinity)

            VStack(alignment: .leading, spacing: 10) {
                sectionTitle("Mission History", systemImage: "clock.arrow.circlepath")
                missionPanel {
                    if summary.visibleMissions.isEmpty {
                        Text("No mission history yet.")
                            .font(.system(size: 12))
                            .foregroundStyle(Color.supraTextSecondary)
                    } else {
                        ForEach(Array(summary.visibleMissions.prefix(8))) { mission in
                            Button {
                                selection = mission.id
                            } label: {
                                HStack(alignment: .top, spacing: 10) {
                                    Circle()
                                        .fill(color(for: mission.status))
                                        .frame(width: 8, height: 8)
                                        .padding(.top, 5)
                                    VStack(alignment: .leading, spacing: 3) {
                                        Text(mission.title)
                                            .font(.system(size: 12, weight: .semibold))
                                            .foregroundStyle(Color.supraText)
                                            .frame(maxWidth: .infinity, alignment: .leading)
                                        Text("\(mission.lifecycle) · \(mission.authority)")
                                            .font(.system(size: 10))
                                            .foregroundStyle(Color.supraTextSecondary)
                                        if let nextMission = mission.nextMission {
                                            Text(nextMission)
                                                .font(.system(size: 10))
                                                .foregroundStyle(Color.supraTextTertiary)
                                                .lineLimit(2)
                                        }
                                    }
                                }
                                .padding(.vertical, 4)
                            }
                            .buttonStyle(.plain)
                        }
                    }
                }
            }
            .frame(maxWidth: .infinity)
        }
    }

    private func queueCard(title: String, missions: [ExecutiveContextSnapshot.MissionSummaryItem], color: Color) -> some View {
        VStack(alignment: .leading, spacing: 10) {
            HStack {
                Text(title)
                    .font(.system(size: 13, weight: .semibold))
                    .foregroundStyle(Color.supraText)
                Spacer()
                Text("\(missions.count)")
                    .font(.system(size: 13, weight: .bold))
                    .foregroundStyle(color)
            }
            if missions.isEmpty {
                Text("No mission")
                    .font(.system(size: 12))
                    .foregroundStyle(Color.supraTextSecondary)
            } else {
                ForEach(missions.prefix(4)) { mission in
                    Button {
                        selection = mission.id
                    } label: {
                        VStack(alignment: .leading, spacing: 4) {
                            Text(mission.title)
                                .font(.system(size: 12, weight: .medium))
                                .foregroundStyle(Color.supraText)
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("\(mission.currentStep) · \(mission.currentStatus)")
                                .font(.system(size: 10))
                                .foregroundStyle(Color.supraTextSecondary)
                                .frame(maxWidth: .infinity, alignment: .leading)
                        }
                        .padding(10)
                        .background(Color.supraGlass)
                        .clipShape(RoundedRectangle(cornerRadius: 10))
                    }
                    .buttonStyle(.plain)
                }
            }
        }
        .padding(16)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Color.supraSurface)
        .clipShape(RoundedRectangle(cornerRadius: 18))
        .overlay(RoundedRectangle(cornerRadius: 18).stroke(Color.supraBorder, lineWidth: 1))
    }

    private func statCard(_ title: String, _ value: String, _ icon: String, _ color: Color) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack {
                Image(systemName: icon)
                    .foregroundStyle(color)
                Spacer()
            }
            Text(title)
                .font(.system(size: 11, weight: .semibold))
                .foregroundStyle(Color.supraTextSecondary)
            Text(value)
                .font(.system(size: 13, weight: .medium))
                .foregroundStyle(Color.supraText)
                .lineLimit(3)
                .frame(maxWidth: .infinity, alignment: .leading)
        }
        .padding(14)
        .frame(maxWidth: .infinity, minHeight: 110, alignment: .topLeading)
        .background(Color.supraSurface)
        .clipShape(RoundedRectangle(cornerRadius: 16))
        .overlay(RoundedRectangle(cornerRadius: 16).stroke(Color.supraBorder, lineWidth: 1))
    }

    private func missionPanel<Content: View>(@ViewBuilder content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            content()
        }
        .padding(16)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Color.supraSurface)
        .clipShape(RoundedRectangle(cornerRadius: 18))
        .overlay(RoundedRectangle(cornerRadius: 18).stroke(Color.supraBorder, lineWidth: 1))
    }

    private func sectionTitle(_ title: String, systemImage: String) -> some View {
        Label(title, systemImage: systemImage)
            .font(.system(size: 15, weight: .bold))
            .foregroundStyle(Color.supraText)
    }

    private var canSubmit: Bool {
        !objective.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    private func submitMission() {
        let trimmedObjective = objective.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedObjective.isEmpty else { return }
        isSubmitting = true
        Task {
            let id = await store.createAndExecuteMission(
                objective: trimmedObjective,
                businessContext: businessContext.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? "User-defined mission from Mission Center" : businessContext.trimmingCharacters(in: .whitespacesAndNewlines),
                technicalContext: technicalContext.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? "Canonical execution through MissionStore, SUPRAMissionBroker and SUPRAExecutionPipeline" : technicalContext.trimmingCharacters(in: .whitespacesAndNewlines),
                priority: priority,
                risk: risk,
                constraints: [
                    "Operate through the canonical Mission object",
                    "Preserve Mission Center as the primary user surface"
                ]
            )
            if let id {
                selection = id.uuidString
                objective = ""
                businessContext = ""
                technicalContext = ""
                priority = .medium
                risk = .medium
            }
            isSubmitting = false
        }
    }

    private func color(for status: String) -> Color {
        switch status.lowercased() {
        case "planned": .supraTextTertiary
        case "active": .supraAccent
        case "blocked": .supraRed
        case "completed": .supraGreen
        default: .supraTextTertiary
        }
    }
}
