// AUTO-GENERATED by ProjectionEngine — derived exclusively from Canonical Knowledge Object
// Canonical ID: can:knowledge:cognitive-cycle-demo-001
// NAMBROCAHORA Tick: 4
// Trace: can:knowledge:tuv5-package → can:knowledge:puchero-candidate → can:knowledge:cognitive-cycle-demo-001

import Foundation

public struct CognitiveCycleStage: Codable, Hashable, Sendable {
    public let id: String
    public let name: String
    public let order: Int
    public let input: String
    public let process: String
    public let output: String
    publiclet validated: Bool
    public let tick: Int64
}

public struct CognitiveCycle: Codable, Hashable, Sendable {
    public let canId: String
    public let canName: String
    public let version: String
    public let stages: [CognitiveCycleStage]
    public let confidence: Double
    public let coherence: Double
    public let nambrohoraRef: Int64

    public static let cycle = CognitiveCycle(
        canId: "can:knowledge:cognitive-cycle-demo-001",
        canName: "SUPRA Cognitive Cycle Demonstration",
        version: "V1",
        stages: [
            CognitiveCycleStage(
                id: "tuv5",
                name: "TUV5 — Comprendre",
                order: 1,
                input: "conversation, idée, document, code, décision",
                process: "Transformer en connaissance structurée",
                output: "Knowledge Package V1",
                validated: true,
                tick: 1
            ),
            CognitiveCycleStage(
                id: "puchero",
                name: "PUCHERO — Mûrir",
                order: 2,
                input: "Knowledge Package",
                process: "Lier les concepts, rechercher les contradictions, fusionner les doublons, accumuler les preuves, mesurer la cohérence",
                output: "Knowledge Candidate",
                validated: true,
                tick: 2
            ),
            CognitiveCycleStage(
                id: "canonico",
                name: "CANNoNICO — Canoniser",
                order: 3,
                input: "Knowledge Candidate",
                process: "Transformer en représentation officielle avec identité, définitions, responsabilités, relations, contraintes, preuves",
                output: "Canonical Knowledge Object",
                validated: true,
                tick: 3
            ),
            CognitiveCycleStage(
                id: "projection",
                name: "ProjectionEngine — Projeter",
                order: 4,
                input: "Canonical Knowledge Object",
                process: "Produire des projections dans 8 formats gouvernés",
                output: "Projections (Swift, Bash, JSON, Markdown, YAML, API, HTML, SQL)",
                validated: true,
                tick: 4
            ),
            CognitiveCycleStage(
                id: "runtime",
                name: "Runtime — Interpréter",
                order: 5,
                input: "Projections",
                process: "Interpréter, exécuter, tracer, prouver, boucler",
                output: "Execution Proof with Feedback Loop",
                validated: true,
                tick: 5
            )
        ],
        confidence: 0.91,
        coherence: 0.92,
        nambrohoraRef: 4
    )
}
