-- AUTO-GENERATED by ProjectionEngine — derived exclusively from Canonical Knowledge Object
-- Canonical ID: can:knowledge:cognitive-cycle-demo-001
-- NAMBROCAHORA Tick: 4

CREATE TABLE IF NOT EXISTS supra_cognitive_cycle (
    can_id TEXT PRIMARY KEY,
    can_name TEXT NOT NULL,
    can_version TEXT NOT NULL DEFAULT 'V1',
    stage TEXT NOT NULL,
    stage_order INTEGER NOT NULL,
    input_text TEXT,
    output_text TEXT,
    validated INTEGER NOT NULL DEFAULT 0,
    confidence REAL NOT NULL,
    coherence REAL NOT NULL,
    nambrohora_ref INTEGER NOT NULL,
    compiled_at INTEGER NOT NULL
);

INSERT OR REPLACE INTO supra_cognitive_cycle VALUES
('can:knowledge:cognitive-cycle-demo-001', 'SUPRA Cognitive Cycle Demonstration', 'V1', 'tuv5', 1, 'conversation, idée, document, code, décision', 'Knowledge Package V1', 1, 0.91, 0.92, 4, 1753862400000);
INSERT OR REPLACE INTO supra_cognitive_cycle VALUES
('can:knowledge:cognitive-cycle-demo-001', 'SUPRA Cognitive Cycle Demonstration', 'V1', 'puchero', 2, 'Knowledge Package', 'Knowledge Candidate', 1, 0.91, 0.92, 4, 1753862400000);
INSERT OR REPLACE INTO supra_cognitive_cycle VALUES
('can:knowledge:cognitive-cycle-demo-001', 'SUPRA Cognitive Cycle Demonstration', 'V1', 'canonico', 3, 'Knowledge Candidate', 'Canonical Knowledge Object', 1, 0.91, 0.92, 4, 1753862400000);
INSERT OR REPLACE INTO supra_cognitive_cycle VALUES
('can:knowledge:cognitive-cycle-demo-001', 'SUPRA Cognitive Cycle Demonstration', 'V1', 'projection', 4, 'Canonical Knowledge Object', 'Projections in 8 formats', 1, 0.91, 0.92, 4, 1753862400000);
INSERT OR REPLACE INTO supra_cognitive_cycle VALUES
('can:knowledge:cognitive-cycle-demo-001', 'SUPRA Cognitive Cycle Demonstration', 'V1', 'runtime', 5, 'Projections', 'Execution Proof with Feedback', 1, 0.91, 0.92, 4, 1753862400000);
